- create_aio_app/template_project/Makefile
- create_aio_app/template_project/README.md
> Stop and remove containers, networks, images, and volumes
For clean up.
> Add clean target

- .travis.yml
- Makefile
- setup.py
* cleanup yaml file syntax
* update setup.py to follow best practices
* enable pyroma on flake check
> Cleanup ci and setup.py

- create_aio_app/main.py
- create_aio_app/utils/config.py
- setup.py
What was done:
- Better output for already existing path
- minor - dropped redundant f-string :)
> Better output for existing path.

- create_aio_app/template/{{cookiecutter.project_name}}/Makefile
- create_aio_app/template/{{cookiecutter.project_name}}/conftest.py
- create_aio_app/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/utils/common.py
- Fixed import to utils on `conftest` (because of this test command was broken)
- Fixed typo in path to config
> Little polishing

- create_aio_app/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/app.py
What was done:
- Fixed typo `close_database` instead of `init_database` on cleanup
> Fixed cleanup closing database

- create_aio_app/main.py
- create_aio_app/template/hooks/pre_gen_project.py
Project name not validated if in created prompt mode
> Fixed name validation in prompt mode

- create_aio_app/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/app.py
Close redis properly, minor cleanup
> fix redis closing

- create_aio_app/template/{{cookiecutter.project_name}}/requirements/development.txt
- create_aio_app/template/{{cookiecutter.project_name}}/requirements/production.txt
- create_aio_app/template/{{cookiecutter.project_name}}/setup.py
- create_aio_app/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/app.py
Package versions have been removed so that the user can freeze the latest libraries himself after creating the project.
> Freezing Python's Dependency

- Makefile
- create_aio_app/template/{{cookiecutter.project_name}}/Makefile
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/index.rst
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/documentation.rst
- create_aio_app/template/{{cookiecutter.project_name}}/requirements/documentation.txt
- requirements-dev.txt
> docs: added docs about documentation block and added linter for checking rst files

- create_aio_app/template/{{cookiecutter.project_name}}/docker-compose.yml
> feat: added color output from docker

- README.md
Hi there! Thank you for the great project. 
PR fixes #43
> Fix for problem with picture in pypi description

- CONTRIBUTORS.txt
- create_aio_app/__init__.py
- setup.py
Added support for [setuptools_scm](https://github.com/pypa/setuptools_scm). Closes #91
> Support for setuptools_scm

- CONTRIBUTORS.txt
- create_aio_app/template/{{cookiecutter.project_name}}/Makefile
Replace all {{ cookiecutter.project_name }} to PROJECT_NAME into Makefile
No
94
* The format is `<Name> <Surname>`.
* Please keep alphabetical order, the file is sorted by names. 
> # 94: replace variable

- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/index.rst
Removed reference to py-modindex.html, which causes 404 error.
No.
#101 
* The format is `<Name> <Surname>`.
* Please keep alphabetical order, the file is sorted by names. 
> fix: removed ref `modindex`

- CONTRIBUTORS.txt
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/index.rst
Added new contributor 
* The format is `<Name> <Surname>`.
* Please keep alphabetical order, the file is sorted by names. 
> added new contributor

- .git_archival.txt
- .gitattributes
- setup.py
> Integrate setuptools-scm-git-archive

- README.md
Add a PyPI badge
None
Resolves #121
> Add a PyPI badge to README

- README.md
- create_aio_app/main.py
- create_aio_app/template/cookiecutter.json
- create_aio_app/template/{{cookiecutter.project_name}}/requirements/production.txt
- create_aio_app/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
- create_aio_app/utils/config.py
Choosing uvloop is possible now. #99
> Uvloop choosing option

- CONTRIBUTORS.txt
- create_aio_app/template/{{cookiecutter.project_name}}/Makefile
- create_aio_app/template/{{cookiecutter.project_name}}/README.md
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/commands.rst
- create_aio_app/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/utils/check-requirements.py
Created command in Makefile for update python dependencies #51
> [WIP] Created command for update python dependencies

- CONTRIBUTING.md
- CONTRIBUTORS.txt
- setup.py
> issue 122 project_urls & contributors

- README.md
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/aiohttp_quick_start.rst
- requirements-dev.txt
- setup.py
Python version 3.5 has removed from supported
#144 
> Python version 3.5 has removed from supported

- CONTRIBUTING.md
- README.md
- create_aio_app/template/{{cookiecutter.project_name}}/README.md
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/aiohttp_quick_start.rst
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/commands.rst
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/documentation.rst
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/tests.rst
Hey! Thanks for the great library, loved it! I just thought I'd make a simple contribution to docs.
Updating the docs
No
None
-----
[View rendered CONTRIBUTING.md](https://github.com/paulefoe/create-aio-app/blob/update-docs/CONT …
> Update the docs

- README.md
-----
[View rendered README.md](https://github.com/Nomanpathan/create-aio-app/blob/master/README.md)
> I thought that readme should be more clear and attractive. When I started using gitHub it really use to affect my mind

- .gitignore
- create_aio_app/template/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/templates/index.html
> minor refactoring add vscode and idea to ignore file

- .github/workflows/python-publish.yml
- .github/workflows/tests.yaml
> feat: moved to gh actions

- CONTRIBUTORS.txt
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/index.rst
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/aiohttp_quick_start.rst
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/documentation.rst
- create_aio_app/template/{{cookiecutter.project_name}}/docs/source/pages/tests.rst
Just fixed some grammatical issues in the docs.
No changes in behavior for the user.
Issue #319 
> Fixed grammatical and stylistic issues in the documentation.
